version: '3'
services:
  soxery-server:
    build: .
    ports:
      - "4000:80"
    volumes:
      - .:/app
    environment:
      PORT: 80
      DEBIAN_FRONTEND: noninteractive
      NPM_CONFIG_LOGLEVEL: error